### ISSUE TITLE
[Bug]: Multiple auto commits and push

### ISSUE THREAD

**Issue by slabzzz** [denolehov/obsidian-git#239] opened 2022-05-19 16:51 UTC
### Describe the bug

Settings
<img width="931" alt="image" src="https://user-images.githubusercontent.com/100169858/169354671-9c5ebe72-2d00-4cf1-8beb-cccaf0315e45.png">

<img width="953" alt="image" src="https://user-images.githubusercontent.com/100169858/169354744-73e666a2-3d62-4581-8724-1cb17ee4e266.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/100169858/169354777-97d221c2-b056-4b91-ae5f-2abed353a6cf.png">

<img width="936" alt="image" src="https://user-images.githubusercontent.com/100169858/169354792-034d8722-88d0-463e-a9bc-85ce09a60e96.png">

Often times I get 2-3 commit/push messages when I am doing auto-backup after edits.

### Steps to reproduce

No idea. Happened after update.

### Operating system

macOS

### Plugin version

1.25.3

**Comment by Vinzent03** [comment] 2022-06-09 12:02
Sorry, but I'm unable to reproduce your issue. It does one commit and push 1 minute after the last change.

**Comment by slabzzz** [comment] 2022-06-09 21:04
Not getting anymore

**Comment by Vinzent03** [comment] 2022-06-09 21:11
Then I will close this for now. Just comment and I will reopen it.

**Closed by Vinzent03** 2022-06-09 21:11 UTC
