### ISSUE TITLE
[Bug]: Cannot run git command - ubuntu 21.04.

### ISSUE THREAD

**Issue by elutek** [denolehov/obsidian-git#194] opened 2022-02-26 21:54 UTC
### Describe the bug

I'm seeing "Cannot run git command" in obsidian on my linux box. Console shows "Error: spawnSync /usr/bin/git ENOENT", but this *is* the correct path. Git works no problem on command-line so I've been pulling and pushing manually but it's tiring and when I forget it, then I ended one once with a nasty rebase.

I'm on recent linux (ubuntu 21.04). This git path is correct - and I tried various ones, and everything is
on PATH, so this is likely not related to path, but maybe to some permissions? Obsidian is installed via snap. Would appreciate any advice on how to debug this.

Thanks!

PS. on my mac, obsidian-git worked out of the box - using the same notes repo in github.

### Relevant errors (if available)

```shell
VM122:11590 Error: spawnSync /usr/bin/git ENOENT
    at Object.spawnSync (internal/child_process.js:1067)
    at spawnSync (child_process.js:611)
    at SimpleGit.isGitInstalled (eval at <anonymous> (app.js:1), <anonymous>:11586:56)
    at SimpleGit.eval (eval at <anonymous> (app.js:1), <anonymous>:11487:17)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:66:61)
    at new Promise (<anonymous>)
    at __async (eval at <anonymous> (app.js:1), <anonymous>:50:10)
    at SimpleGit.checkRequirements (eval at <anonymous> (app.js:1), <anonymous>:11486:12)
    at ObsidianGit.eval (eval at <anonymous> (app.js:1), <anonymous>:14692:46)
```

### Steps to reproduce

Be on Ubuntu 21.04.
Install git via apt.
Install obsidian via snap.
Create github repo, configure git auth, pull the repo.
Install obsidian-git plugin from community.
Just run obsidian - one of the first things to see is "Cannot run git" error message.

### Operating system

Linux

**Comment by Vinzent03** [comment] 2022-02-27 12:48
Duplicate of #92, #89

**Closed** 2022-03-01 10:36 UTC

**Comment by elutek** [comment] 2022-03-01 18:44
Resolved now: I was getting the same problem with flatpak, but appimage worked immediately. 

Thanks!

**Comment by joshxyzhimself** [comment] 2022-04-18 10:23
> Duplicate of #92, #89
> 
> As stated in the [wiki](https://github.com/denolehov/obsidian-git/wiki/Installation#linux) installing Obsidian via Snap is not supported.
> 
> Please installing Obsidian via Flatpak or AppImage.

GOOD LORD after hours and hours of searching, haha.
