### ISSUE TITLE
[Bug]: When cloning a repo, the application crashes

### ISSUE THREAD

**Issue by Komar0ff** [denolehov/obsidian-git#482] opened 2023-03-31 12:25 UTC
### Describe the bug

When cloning the repository, the application crashes. After opening the application again it says "No upstream branch is set. Please select one". I select one and everything repeats.

### Steps to reproduce

1.  Download and install the plugin
2. In the settings of the plugin specify name and password
3. Go to the vault
4. Call the command line by swiping
5. Choose git clone 
6. Enter the link to the deleted branch and the desired data
This starts cloning and after a while the application crashes.

### Expected Behavior

Cloning is successful

### Addition context

On the computer, the plugin works properly. And until recently it worked well on iOS. 
Current repo size 70MB

### Operating system

iOS

### Installation Method

None

### Plugin version

2.19.0

**Comment by Vinzent03** [comment] 2023-03-31 12:43
Duplicate of #349

**Closed by Vinzent03** 2023-03-31 12:43 UTC
