### ISSUE TITLE
Support for rename of files

### ISSUE THREAD

**Issue by BaumiCoder** [denolehov/obsidian-git#579] opened 2023-08-15 11:02 UTC
# Feature description
If I rename a note (or a file in general) in obsidian, it should be also renamed in git (`git mv`).
# Use case for the feature
I want to rename one of my notes in obsidian. If there are many other notes with links to this note, I change the name directly in obsidian to update all links to the new name. The renamed note should be also rename in git, so that the history of the file doesn't get lost.
## Actual workaround
Actual I have to do a workaround like this to achieve it:

1. Rename the note in obsidian, to update the links.
2. Rename it back to the old name outside of obsidian, with file explorer or on the shell.
3. Make an `git mv` on the note.

# Further ideas for the feature
- A option in the settings to switch it the "automatic git move" on and off could be wise. (Default ON?)
- Maybe the moving of a file from one folder to another should be also handled. I doesn't see big benefit of that, but technically it is quit similar.

**Comment by Vinzent03** [comment] 2023-08-15 11:21
You just have to stage the files. Git will identify the rename and properly mark it as a rename. 
Duplicate of #62

**Closed by Vinzent03** 2023-08-15 11:21 UTC

**Comment by BaumiCoder** [comment] 2023-08-15 12:38
Thanks for the quick response. 

I expect that a command like `git log renamedNote.md` also shows the commits to the file before the rename (like in SVN). That isn't the case. But now I looked at it in detail. That's the normal behaviour. Using `git mv` doesn't make it better.
