### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of null (reading 'slice')

### ISSUE THREAD

**Issue by hsimonfroy** [denolehov/obsidian-git#544] opened 2023-06-26 16:24 UTC
### Describe the bug

Suddenly this error appears when trying to clone or pull from a remote repository on Android Phone and Android Pad. Works fine on PC.

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
Can't find an easy access to devtools on Android Phone and Android Pad. And the error doesn't occure on PC.
```

### Steps to reproduce

* Create a github repository with a random .md file. 
* Open Obsidian on Android Phone or Android Pad
* Add credentials, clone the repository (selecting default options).

This yields:
> TypeError: Cannot read properties of null (reading 'slice')

### Expected Behavior

A successful cloning or pulling. This type of setup was working last week.

### Operating system

Android

### Installation Method

None

### Plugin version

current last version 2.20.4

**Comment by Vinzent03** [comment] 2023-06-27 20:49
Sorry, but I can't reproduce your issue. I tried a private repo in a new vault. Do you have that issue for every clone?

**Comment by Vinzent03** [comment] 2023-06-28 12:04
Oh yeah it is, thanks!

Duplicate of #379

**Closed by Vinzent03** 2023-06-28 12:04 UTC
