### ISSUE TITLE
[Bug]: Trying to pull or clone cause Obsidian to crash on Android 11

### ISSUE THREAD

**Issue by voltamass** [denolehov/obsidian-git#352] opened 2022-10-25 20:53 UTC
### Describe the bug

Since version 1.4 of Obsidian Mobile and 2.7 of Obsdian-Git, trying to pull or clone my repo cause the app to crash.
Using another smaller repo with a placeholder file, pulling, cloning and pushing still work as intended.

### Steps to reproduce

Install Obsidian Git
Configure Obsidian Git (User, Password)
Select "Obsidian Git: Clone an exisiting remote repo" from command list
Insert respective URL and confirm mentioned questions

### Expected Behavior

I should be able to pull or clone the repo.

### Addition context

The repo weight about 2 Mb, all of them .md files except for 2 images.
700 files in 64 folders.

### Operating system

Android

### Plugin version

2.8

**Comment by Vinzent03** [comment] 2022-11-08 11:26
Strange that this already happens for 2mb on your device. Duplicate of #307

**Closed** 2022-11-08 11:26 UTC
