### ISSUE TITLE
MergeNotSupported on pull

### ISSUE THREAD

**Issue by spesthecat** [denolehov/obsidian-git#380] opened 2022-11-18 21:30 UTC
I've been dealing with an annoying issue for the past week. I use Obsidian git on my mac and iPhone. 

## Issue
When pulling on mobile, I get `MergeNotSupported` error, "merges with conflicts are not supported". This is annoying because I haven't found any reliable way to resolve it other than throwing the whole repo away and cloning from remote. Could there possibly be a command to `git reset --hard` on mobile? That is- discard local changes and then pull? Most of the time I don't care about the changes I've made on mobile, and it's next to impossible to try to revert the changes.

I've tried going to the source control panel and discarding the changes that pop up there to the point where it shows no changes, but I still get `MergeNotSupported`.

Is this something that's within the capabilities of isomorphic-git?

**Comment by fea17e86** [comment] 2022-11-20 18:16
I have the same issue. I can't even find out which is the conflicting file.

**Comment by nesou2** [comment] 2022-11-24 10:14
I also have this issue. At the moment the best thing you can do is push to a branch, clean up the merge conflict on another device, then clone the cleaned repo. This isn’t that bad honestly, but it would be nice to make it easy to “just delete all changes and re-clone the repo”.

**Comment by Vinzent03** [comment] 2022-11-26 12:43
Duplicate of #340

**Closed by Vinzent03** 2022-11-26 12:43 UTC
