### ISSUE TITLE
[Bug]: the plugin freeze obsidian 

### ISSUE THREAD

**Issue by realliyifei** [denolehov/obsidian-git#180] opened 2022-02-06 05:54 UTC
### Describe the bug

I just downloaded this plugin and every time I try to enter, the obsidian app will froze forever (only this plugin).

The screenshot is here FYI,

<img width="996" alt="image" src="https://user-images.githubusercontent.com/32441766/152669418-f272830f-6696-4aba-af5c-0f7dd20df14a.png">

### Steps to reproduce

(Just enter the plugin and things happen). I don’t know how to reproduce.

### Operating system

macOS

**Comment by gerbsen** [comment] 2022-02-07 13:18
Duplicate of https://github.com/denolehov/obsidian-git/issues/69

**Closed** 2022-02-10 02:42 UTC

**Comment by realliyifei** [comment] 2022-02-10 05:26
thanks; it seems work today
