### ISSUE TITLE
[Bug]: Error when automatically pushing to remote repo on GitHub

### ISSUE THREAD

**Issue by hansiebo** [denolehov/obsidian-git#369] opened 2022-11-06 13:52 UTC
### Describe the bug

Obsidian Git commits my changes (after file change and in regular intervals) as expected, but when Obsidian Git is trying to push them (automatically) to a remote repository on GitHub, it does not work and I get an error notification.

- No such file or directory
- could not read username.

When I manually push the changes (in terminal via "git push") it works.
That means my system/repo is connected to the remote.

Error Notification:
![image](https://user-images.githubusercontent.com/111209756/200174212-7cfe24d9-2a31-415f-90a6-ac08bca7dfa2.png)

### Relevant errors (if available)

```shell
See screenshot of the error notification above.
```

### Steps to reproduce

- I initialized my obsidian vault as a git repo and set a github repo as a remote.
- Manually pushing changes from terminal after commit works.
- See Obsidian git settings below under "Additional context".

### Expected Behavior

I expect the changes to be pushed to the remote github repo as specified in the settings.

### Addition context

**Plugin Settings:**

![image](https://user-images.githubusercontent.com/111209756/200174253-140ffac8-b7ab-4a33-b342-19d9af063c54.png)

![image](https://user-images.githubusercontent.com/111209756/200174266-6b1f287f-9cfc-4ab8-81da-fe439fbee0b0.png)

![image](https://user-images.githubusercontent.com/111209756/200174293-26e9fab4-b020-450c-ae1e-df6ca7112dfb.png)

![image](https://user-images.githubusercontent.com/111209756/200174302-3e4791e0-798c-4499-a9a6-9f2aa1ce63bf.png)

![image](https://user-images.githubusercontent.com/111209756/200174323-adf0158e-b7b7-4a00-b9c8-8c1862259db3.png)

### Operating system

Linux

### Plugin version

2.9.4

**Comment by mafsi** [comment] 2022-11-06 14:50
Same here!

**Comment by hansiebo** [comment] 2022-11-08 22:46
@Vinzent03 any idea what the issue might be? Seems like there are several issues hinting at the same problem.

**Comment by Vinzent03** [comment] 2022-11-08 22:52
@hansiebo From your error message you use the github cli as credential manager? Haven't seen this before. Seems like it can't find the `gh` binary? Are you sure it's installed at that location?

**Comment by hansiebo** [comment] 2022-11-09 00:18
yes, github cli.

I can push the repo manually via "git push" from the command line to github. That means it should be installed properly, right?

@Vinzent03

**Comment by beluzzi** [comment] 2022-11-09 12:18
I have the exact same issue. Same configuration as yours. Pushing from terminal works. gh is installed under usr/bin/gh and works in terminal (verified via "gh auth status").

**Comment by hansiebo** [comment] 2022-11-10 19:23
It seems like we are at least 5 people then who are facing this issue. 3 in this thread.
And these two issues seem related:
https://github.com/denolehov/obsidian-git/issues/367
https://github.com/denolehov/obsidian-git/issues/369

**Comment by Metal-Toilet** [comment] 2022-11-11 18:23
I fixed by pushing with a ssh key as opposed to https

**Comment by hansiebo** [comment] 2022-11-14 21:09
I  just tried it with an ssh key, but did not work for me / could not get it to work.

**Comment by Zabooby** [comment] 2022-11-14 21:17
Getting the same error notification too.

**Comment by evang522** [comment] 2022-11-29 07:28
I am getting a similar error, but with using an SSH key.  (Fedora Linux)

![image](https://user-images.githubusercontent.com/29560181/204465367-5fdc1c2d-60ec-4176-bb92-27910d2cfb2f.png)


This started happening somewhere between the end of October and November 11th-ish, I didn't change anything on my side other than regularly updating obsidian-git. 

My CLI works perfectly fine, only when Obsidian tries to push does it encounter errors.

**Comment by evang522** [comment] 2022-12-01 05:54
Update to my previous post. I fixed this by running: 

`chmod 600 ~/.ssh/config`

As should have been obvious from the SSH error, it was a bad permissions issue.

**Comment by Vinzent03** [comment] 2022-12-07 20:55
I can't execute the `gh` binary from withing Obsidian, but other binaries like `git` or simply `cat` can be executed. I don't know why, because the permissons are the same. So I don't know how to resolve this issue.
I suggest you to use a different credential helper.

**Comment by BorisZubchenko** [comment] 2022-12-28 20:51
Installing Obsidian with AppImage instead Flatpak solved the issue for me.

**Comment by kematzy** [comment] 2023-01-11 06:07
**A POSSIBLE SOLUTION?**

I too were getting these `Username for 'https://github.com': No such device or address` errors. 

My solution was to change the Git Remote "origin" value from:

```https://github.com/[USERNAME]/[REPO].git```  to  ```git@github.com:[USERNAME]/[REPO].git``` 

in the Obsidian vault / Git repository.  After that everything seemed to work fine.

Perhaps this could be added as a Tips & Tricks note or otherwise indicated in the documentation?

**Comment by Vinzent03** [comment] 2023-01-11 08:18
You changed the remote url from https to ssh. The user has ssh keys to be set up for this to work.

**Comment by SelinJodhani** [comment] 2023-01-29 17:34
> **A POSSIBLE SOLUTION?**
> 
> I too were getting these `Username for 'https://github.com': No such device or address` errors.
> 
> My solution was to change the Git Remote "origin" value from:
> 
> `https://github.com/[USERNAME]/[REPO].git` to `git@github.com:[USERNAME]/[REPO].git`
> 
> in the Obsidian vault / Git repository. After that everything seemed to work fine.
> 
> Perhaps this could be added as a Tips & Tricks note or otherwise indicated in the documentation?

changed where exactly? couldn't find it in extenstion settings.

**Comment by Vinzent03** [comment] 2023-02-06 21:47
I tried to come up with the most general auth instructions as possible, without having to install too much packages or write many config. I summarized it [here](https://github.com/denolehov/obsidian-git/wiki/Authentication). May you try it out and tell me how it's working? I can't test it on all operating systems. Especially not macOS.

**Closed** 2023-03-01 11:42 UTC

**Comment by obarbier** [comment] 2023-03-09 00:22
I can confirm @BorisZubchenko  Answer worked for me

> Installing Obsidian with AppImage instead Flatpak solved the issue for me.

**Comment by savvasenok** [comment] 2023-10-17 20:51
> > **A POSSIBLE SOLUTION?**
> > I too were getting these `Username for 'https://github.com': No such device or address` errors.
> > My solution was to change the Git Remote "origin" value from:
> > `https://github.com/[USERNAME]/[REPO].git` to `git@github.com:[USERNAME]/[REPO].git`
> > in the Obsidian vault / Git repository. After that everything seemed to work fine.
> > Perhaps this could be added as a Tips & Tricks note or otherwise indicated in the documentation?
> 
> changed where exactly? couldn't find it in extenstion settings.

write in the console in your directory `git remote set-url origin <remote_ssh_url>`. Worked for me
