### ISSUE TITLE
Feature Request: Push on Obsidian close

### ISSUE THREAD

**Issue by mdroidian** [denolehov/obsidian-git#63] opened 2021-04-06 03:49 UTC
Sometimes I forget to manually push before closing Obsidian.

Would it be possible to force push on manually closing Obsidian? (ie, clicking the 'X' in the top right corner, not a force close)

**Comment by Vinzent03** [comment] 2021-04-06 11:22
Duplicate of #13

**Closed by Vinzent03** 2021-04-06 11:22 UTC
