### ISSUE TITLE
[Bug]: Crashes when syncing 10k notes

### ISSUE THREAD

**Issue by moonspeaking** [denolehov/obsidian-git#403] opened 2022-12-14 11:21 UTC
### Describe the bug

Git pull or push

### Relevant errors (if available)

```shell
time: 1671016133722
msg: java.lang.OutOfMemoryError: Failed to allocate a 295960592 byte allocation with 100663296 free bytes and 112MB until OOM, target footprint 251567856, growth limit 268435456
stacktrace: java.lang.OutOfMemoryError: Failed to allocate a 295960592 byte allocation with 100663296 free bytes and 112MB until OOM, target footprint 251567856, growth limit 268435456
	at java.util.Arrays.copyOf(Arrays.java:3161)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at com.capacitorjs.plugins.app.AppPlugin.requestUrlAndroid(AppPlugin.java:236)
	at com.capacitorjs.plugins.app.AppPlugin.lambda$requestUrl$2$com-capacitorjs-plugins-app-AppPlugin(AppPlugin.java:157)
	at com.capacitorjs.plugins.app.AppPlugin$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:1013)
```

### Steps to reproduce

Synchronization does not work both ways, nothing happens in windows, crashes on Android

### Addition context

Android and Windows.
10000 notes

### Operating system

Android

### Plugin version

2.13.0

**Comment by Vinzent03** [comment] 2022-12-16 14:46
Duplicate of #307

**Closed** 2022-12-16 14:46 UTC
