### ISSUE TITLE
Feature request: Support Git move

### ISSUE THREAD

**Issue by bioe007** [denolehov/obsidian-git#711] opened 2024-03-25 01:15 UTC
## Problem to solve
Obsidian's native move commands causes git to consider the file as deleted, breaking the history for a specific note. 

## Why it's important
Many note-taking methodologies rely on a 'create first, organize later' approach so often there are many notes that need to be moved. If a user wants to keep the editing history for a note they have to perform "git mv" from the command line. 

I think it's important to note the user must _remember_ to do this for any notes they ever want to move. Since the goal of the note-taking app is to reduce cognitive overhead it seems natural that the obsidian-git plugin should also make it easier to "do the right thing"

## Proposed solutions/strategies
1. monkey patch or decorate Obisidian's native calls to "move note" such that any existing or possibly even new ways to move notes "do the right thing"
2. Context menu option just below 1st party "move note" commands
3. command pallet "Git: move note" command creates modal with from/to and [stretch] display small preview
4. React to obisidian's 1st party file moves and do some magical-git-fu _after_ the file is moved to keep tracking history across file moves

## Notes

The list of "proposed solutions" is not comprehensive, and some aren't mutually exclusive, just spit-balling some ideas of how it could look. Also, I have no idea what's possible within obsidian's public apis.

**Comment by Vinzent03** [comment] 2024-03-25 11:25
Duplicate of #579

**Closed by Vinzent03** 2024-03-25 11:25 UTC
