### ISSUE TITLE
[Bug]: The whole interface Get stuck  when git commit or git push

### ISSUE THREAD

**Issue by Abirdcfly** [denolehov/obsidian-git#105] opened 2021-08-19 09:46 UTC
### Describe the bug

The whole interface Get stuck  when git commit or git push. I have to wait several seconds.maybe 3 or 5 seconds

### Steps to reproduce

Just use it.

### Addition context

This is a pretty great plugin. It's my reason to stay on obsidian not other markdown editor.Really Thanks.

**Comment by Vinzent03** [comment] 2021-08-20 14:30
I guess you are on MacOS. I think this is a duplicate of #69

**Comment by Abirdcfly** [comment] 2021-08-20 16:12
Yup.Let us close this.Use#68

**Closed** 2021-08-20 16:13 UTC
