### ISSUE TITLE
Can't do any access to remote repo from Obsidian-git

### ISSUE THREAD

**Issue by troyane** [denolehov/obsidian-git#167] opened 2022-01-18 11:24 UTC
**Environment:** Win10, Obsidian 0.13.19, Obsidian-Git 1.20.0.

Getting this error:
```
git obsidian error: Pull failed git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
![image](https://user-images.githubusercontent.com/477468/149927978-0542b970-19f1-40b8-ba3f-4260c2d45f4f.png)

While access to repo from git-bash works flawlessly:
![image](https://user-images.githubusercontent.com/477468/149928520-91064560-2a7d-417d-ae22-441a48b0f147.png)

Any recommendations?

**Comment by Vinzent03** [comment] 2022-01-18 14:23
I see you have to enter your passphrase in the terminal. But it doesn't ask you for it from Obsidian. So it can't use the ssh key properly and fails to authenticate. Duplicate of #42. See the comments there for more details.

**Closed by Vinzent03** 2022-01-18 14:23 UTC

**Comment by troyane** [comment] 2022-01-18 15:54
@Vinzent03 Thanks for a quick response. Unfortunately, it doesn't help me.  I can run `ssh-agent`, but when I do `ssh-add` or `ssh-add ~/.ssh/id_rsa.pub` it says:
```
Could not open a connection to your authentication agent.
```

**Comment by Vinzent03** [comment] 2022-01-23 13:52
Sorry for the late answer. Does anything from [this stackoverflow answer](https://stackoverflow.com/a/17848593 help?

**Comment by ROODAY** [comment] 2022-01-27 18:18
@Vinzent03 @troyane I think I have a fix! I'm running Windows 10, and when I originally made #173 I was using cmder as my shell (it was a pretty funky setup that used cmd + a bunch of other programs/plugins to simulate Linux commands), but I wanted to simplify the issue so I switched to using PowerShell 7 through Windows Terminal. 

I did the following to save my SSH key passphrase (last line was just to verify it was added):
```powershell
Set-Service ssh-agent -StartupType Automatic
Start-Service ssh-agent
ssh-add C:\path\to\your\ssh\key\id_rsa
ssh-add -l
```
Then I added this environment variable: `GIT_SSH=C:\Windows\System32\OpenSSH\ssh.exe` and ran these commands: `git config --global credential.helper store`  and `git config --global core.sshCommand C:/Windows/System32/OpenSSH/ssh.exe`.

Now, whenever I start Windows Terminal/PowerShell 7, I don't have to type my passphrase anymore, I can just SSH to other machines or git push without a problem. Obsidian Git now also works (it kept failing until the last step of `git config --global core.sshCommand C:/Windows/System32/OpenSSH/ssh.exe`). Hope this helps!

**Comment by troyane** [comment] 2022-02-13 12:34
@Vinzent03 Unfortunately nothing from that SO link helped me.

@ROODAY Yahoo! You've made it :D 
Finally, I can push from Obsidian. Here are a few of my tips (you can add them to your post, so anyone with the same problem may quickly resolve it):
Keep in mind that you need to run PowerShell as admin, so do:
```powershell
start-process powershell -verb runas
```
Unfortunately, this command didn't work for me:
```bash
git config --global credential.helper store
```
so I need to do:
```bash
git config --global --unset-all credential.helper
```

Thanks again!

**Comment by shiva246** [comment] 2023-12-29 17:17
The other workaround I found was instead of setting the remote URL as **ssh,** I setup the remote URL as **https**. This worked for me.
