### ISSUE TITLE
[Bug]: Crash on cloning repo Android

### ISSUE THREAD

**Issue by mathisgauthey** [denolehov/obsidian-git#384] opened 2022-11-23 07:04 UTC
### Describe the bug

I followed the [instructions](https://github.com/denolehov/obsidian-git/wiki/Installation#mobile) for mobile in order to stop using Termux for my sync.

At first my identification to Github had issues. I solved it by using a token and not a password, and by starting fresh with a new vault.

But after installing Obsidian-git on my Android, and inputting my logins, I try to clone my repository and then Obsidian crashes a few second after cloning initialisation.

### Relevant errors (if available)

```shell
No error found, the app crashes.
```

### Steps to reproduce

Pixel 4A 5G with Android 13

- Install Obsidian.
- Create new vault
- Install Obsidian Git Plugin
- Add your logins
- Clone repo command in the vault, already having a .obsidian and hence deleting the temporary vault settings created for the setup

### Expected Behavior

Crash just after clone initialization.

### Operating system

Android

### Plugin version

2.10.2

**Comment by Vinzent03** [comment] 2022-11-26 12:08
Duplicate of #307

**Closed by Vinzent03** 2022-11-26 12:08 UTC

**Comment by HarvsG** [comment] 2023-02-01 17:29
@Vinzent03 are you sure that this is a duplicate - none of these reports (including my issue) describe the buffer error. Just straight out crashes. 

Could it be caused by something other than memory problems? Perhaps a conflict in the settings?
If it is a memory issue, could you save on memory by reducing the git clone depth.
https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
