### ISSUE TITLE
[Bug]: xcodebuild[68637:4884123] [MT] DVTPlugInLoading: Failed to load code for plug-in

### ISSUE THREAD

**Issue by michaelpporter** [denolehov/obsidian-git#308] opened 2022-09-13 14:50 UTC
### Describe the bug

After a background update to xcode I started seeing these errors in the log

### Relevant errors (if available)

```shell
plugin:obsidian-git:31456 Error: 2022-09-13 09:21:51.030 xcodebuild[67556:4870159] [MT] DVTPlugInLoading: Failed to load code for plug-in com.apple.dt.IDESimulatorAvailability (/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin), error = Error Domain=NSCocoaErrorDomain Code=3588 "dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, 0x0109): Symbol not found: (_OBJC_CLASS_$_SimDiskImage)
  Referenced from: '/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability'
  Expected in: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator'" UserInfo={NSLocalizedFailureReason=The bundle couldn’t be loaded., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, NSDebugDescription=dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, 0x0109): Symbol not found: (_OBJC_CLASS_$_SimDiskImage)
  Referenced from: '/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability'
  Expected in: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator', NSBundlePath=/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin, NSLocalizedDescription=The bundle “IDESimulatorAvailability” couldn’t be loaded.}, dyldError = dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, 0x0000): Symbol not found: (_OBJC_CLASS_$_SimDiskImage)
  Referenced from: '/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability'
  Expected in: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator'
2022-09-13 09:21:51.051 xcodebuild[67556:4870159] [MT] DVTAssertions: ASSERTION FAILURE in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot2/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-21303/DVTFoundation/PlugInArchitecture/DataModel/DVTPlugIn.m:374
Details:  Failed to load code for plug-in com.apple.dt.IDESimulatorAvailability (/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin)
Please ensure Xcode packages are up-to-date — try running 'xcodebuild -runFirstLaunch'.

NSBundle error: Error Domain=NSCocoaErrorDomain Code=3588 "dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, 0x0109): Symbol not found: (_OBJC_CLASS_$_SimDiskImage)
  Referenced from: '/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability'
  Expected in: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator'" UserInfo={NSLocalizedFailureReason=The bundle couldn’t be loaded., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, NSDebugDescription=dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, 0x0109): Symbol not found: (_OBJC_CLASS_$_SimDiskImage)
  Referenced from: '/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability'
  Expected in: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator', NSBundlePath=/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin, NSLocalizedDescription=The bundle “IDESimulatorAvailability” couldn’t be loaded.}
Object:   <DVTPlugIn: 0x10eb9e4c0>
Method:   -loadAssertingOnError:error:
Thread:   <_NSMainThread: 0x147e0c5f0>{number = 1, name = main}
Hints: 

Backtrace:
  0  0x00000001027a1410
  1  0x00000001027a0aec
  2  0x00000001027a0c6c
  3  0x000000010264f2ac
  4  0x0000000102615118
  5  0x0000000102613528
  6  0x00000001997801b4
  7  0x000000019978f414
  8  0x00000001027e558c
  9  0x00000001027c14b0
 10  0x00000001026133c0
 11  0x00000001026135e0
 12  0x00000001036d72ec
 13  0x00000001036d6ae0
 14  0x00000001036d61e8
 15  0x0000000101074324
 16  0x0000000100c65e0c
sh: line 1: 67559 Abort trap: 6           /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find git 2> /dev/null
git: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find git 2> /dev/null' failed with exit code 34304: (null) (errno=Invalid argument)
xcode-select: Failed to locate 'git', requesting installation of command line developer tools.

    at Object.action (plugin:obsidian-git:24326:25)
    at PluginStore.exec (plugin:obsidian-git:24351:25)
    at eval (plugin:obsidian-git:21944:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (plugin:obsidian-git:21942:16)
    at GitExecutorChain.eval (plugin:obsidian-git:21926:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-git:20775:24)
eval @ plugin:obsidian-git:31456
```

### Steps to reproduce

Having Xcode 14, from what I can tell.

```bash
xcodebuild
2022-09-13 09:45:35.829 xcodebuild[70655:4914365] [MT] DVTPlugInLoading: Failed to load code for plug-in com.apple.dt.IDESimulatorAvailability (/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin), error = Error Domain=NSCocoaErrorDomain Code=3588 "dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, 0x0109): Symbol not found: (_OBJC_CLASS_$_SimDiskImage)
  Referenced from: '/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability'
  Expected in: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator'" UserInfo={NSLocalizedFailureReason=The bundle couldn’t be loaded., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, NSDebugDescription=dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, 0x0109): Symbol not found: (_OBJC_CLASS_$_SimDiskImage)
  Referenced from: '/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability'
  Expected in: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator', NSBundlePath=/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin, NSLocalizedDescription=The bundle “IDESimulatorAvailability” couldn’t be loaded.}, dyldError = dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, 0x0000): Symbol not found: (_OBJC_CLASS_$_SimDiskImage)
  Referenced from: '/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability'
  Expected in: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator'
2022-09-13 09:45:35.849 xcodebuild[70655:4914365] [MT] DVTAssertions: ASSERTION FAILURE in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot2/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-21303/DVTFoundation/PlugInArchitecture/DataModel/DVTPlugIn.m:374
Details:  Failed to load code for plug-in com.apple.dt.IDESimulatorAvailability (/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin)
Please ensure Xcode packages are up-to-date — try running 'xcodebuild -runFirstLaunch'.

NSBundle error: Error Domain=NSCocoaErrorDomain Code=3588 "dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, 0x0109): Symbol not found: (_OBJC_CLASS_$_SimDiskImage)
  Referenced from: '/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability'
  Expected in: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator'" UserInfo={NSLocalizedFailureReason=The bundle couldn’t be loaded., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, NSDebugDescription=dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, 0x0109): Symbol not found: (_OBJC_CLASS_$_SimDiskImage)
  Referenced from: '/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability'
  Expected in: '/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator', NSBundlePath=/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin, NSLocalizedDescription=The bundle “IDESimulatorAvailability” couldn’t be loaded.}
Object:   <DVTPlugIn: 0x600001a0d900>
Method:   -loadAssertingOnError:error:
Thread:   <_NSMainThread: 0x600003e40280>{number = 1, name = main}
Hints:

Backtrace:
  0  0x00000001044a1410
  1  0x00000001044a0aec
  2  0x00000001044a0c6c
  3  0x000000010434f2ac
  4  0x0000000104315118
  5  0x0000000104313528
  6  0x00000001997801b4
  7  0x000000019978f414
  8  0x00000001044e558c
  9  0x00000001044c14b0
 10  0x00000001043133c0
 11  0x00000001043135e0
 12  0x00000001053d72ec
 13  0x00000001053d6ae0
 14  0x00000001053d61e8
 15  0x0000000102d74324
 16  0x0000000102b05e0c
[1]    70655 abort      xcodebuild
```

### Addition context

```bash
xcodebuild -version
Xcode 14.0
Build version 14A309
```
I tried updating `xcodebuild` but it does not have 
```bash
xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

1. Run Roftware Update in System Preferencees
2. Open Terminal
3. run `xcodebuild` this prompts an install of CLI tools

### Operating system

macOS

### Plugin version

2.1.0

**Comment by curtismchale** [comment] 2022-09-13 21:09
@michaelpporter I'm seeing the same issue with macOS version 12.5.1. I have also tried to update xcode which did not resolve the issue.

**Comment by goncalomcorreia** [comment] 2022-09-14 13:16
I have the same issue. Seems to be due to the latest update for xcode.

**Comment by michaelpporter** [comment] 2022-09-14 14:03
More info/Work around:  

I also have git installed via [homebrew](https://brew.sh) `brew install git` which is in my path and works fine.

```shell
type -a git
git is /opt/homebrew/bin/git
git is /usr/bin/git
```

The "core" from xcode has the issue. When I run it I get a prompt to install git.

```shell
/usr/bin/git -version
2022-09-14 08:44:21.187 xcodebuild[65760:6703978] [MT] DVTPlugInLoading: Failed to load code for plug-in com.apple.dt.IDESimulatorAvailability (/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin), error = Error Domain=NSCocoaErrorDomain Code=3588 "dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESimulatorAvailability.ideplugin/Contents/MacOS/IDESimulatorAvailability, 0x0109): Symbol not found: (_OBJC_CLASS_$_SimDiskImage)
....
```

If I update my `Custom Git binary path` in settings it's working.

**Comment by Delusion4013** [comment] 2022-09-15 00:51
I got the same issue with macOS version 12.5, plugin version 2.1.0. I tried to downgrade my obisidian-git plugin version to previous releases but the issue remains. I tried @michaelpporter's suggestion by **updating the plugin setting** with my git path and the issue is solved. The interesting thing is both git path  listed from the `type -a git` command works for me.
![image](https://user-images.githubusercontent.com/41226309/190287874-1b097dcf-3a93-41f0-913f-6ddb131e4df6.png)

**Comment by michaelpporter** [comment] 2022-09-15 01:56
I just found, when I opened xcode it prompted me to install more things. After that git works for both paths. It seems that a proper xcode install could also fix the issue.

**Comment by Vinzent03** [comment] 2022-09-21 10:44
I will close this issue, because it's not related to this plugin, but your local git installation.

**Closed by Vinzent03** 2022-09-21 10:45 UTC

**Comment by fabus961** [comment] 2024-09-26 13:41
ionic cap sync drops: [capacitor] [error] 2024-09-26 15:34:32.780 xcodebuild[91208:1788360] [MT] DVTPlugInLoading: Failed to load code for plug-in com.apple.dt.IDESimulatorFoundation

> I just found, when I opened xcode it prompted me to install more things. After that git works for both paths. It seems that a proper xcode install could also fix the issue.

Same in my case - It occured after I had to agree on a updated license agreement... 

To resolve it I had to start the xcode GUI. On launch it prompted me to update/install Phone Tablet dependencies and I was able to proceed.
