### ISSUE TITLE
[Bug]: Pushing Forbidden when I have git-LFS enabled

### ISSUE THREAD

**Issue by thewildofficial** [denolehov/obsidian-git#151] opened 2021-12-10 20:44 UTC
### Describe the bug

I have recently installed git-LHS and it works fine by itself (am able to push and pull changes from git)

however, I encounter the following error on evoking the "push" command in obsidian
![image](https://user-images.githubusercontent.com/52071834/145638838-194f5840-97b4-4492-bc9f-0803c952bcf6.png)

### Steps to reproduce

- install git-obsidian
- install git-LFS and initialise it in your repository
- attempt to push your local changes

### Expected Behavior

git-Obsidian recognises git-LFS, and pushes changes 

### Operating system

macOS

**Comment by Vinzent03** [comment] 2021-12-10 20:54
Duplicate of #14. Please try the solutions provided there.

**Closed by Vinzent03** 2021-12-10 20:54 UTC

**Comment by thewildofficial** [comment] 2021-12-11 05:37
recommendations worked! thank you
closing issue.
