### ISSUE TITLE
[Bug]: the whole app freezes when i turn on obsidian git

### ISSUE THREAD

**Issue by A6rron** [denolehov/obsidian-git#412] opened 2022-12-30 15:13 UTC
### Describe the bug

hey,
recently i face a problem - the whole app become frooze
when the i turn off obsidian git it fixes 
anyone know the solution

### Steps to reproduce

a

### Operating system

Linux

### Plugin version

2.14.0

**Comment by Vinzent03** [comment] 2023-01-03 17:31
I never heard of this before on Linux. There were some issues on macos, but they go resolved with an electron update #69. Don't know causes this for you. May you open the console (`CTRL + SHIFT + I`) to check potential errors?

**Comment by erikpearson** [comment] 2023-01-18 03:01
I see something similar running Obsidian on Windows 11.  Observed with Obsidian v1.1.9 and Obsidian Git 2.15.0.  When Obsidian Git is enabled, the app becomes completely unresponsive for 5-10 seconds, sometimes more, approximately every 5-10 minutes.  I'm still playing around with configuration to see if corrolates with auto-update interval, but nothing yet.  Notably, if I turn off all auto push/pull settings, I still see this behavior.  The only remedy is to disable Obsidian Git altogether.  I saw nothing in the developer console log to suggest a problem.

**Comment by Banou26** [comment] 2023-05-30 14:28
Got the same error, `obsidian-git`'s `callTaskParser` freeze for ~20s+ every x seconds 
![image](https://github.com/denolehov/obsidian-git/assets/5209149/2a9c4c52-53de-425d-8bcd-4b161c3716b0)

The callstack is
```
ChildProcess._handle.onexit
node:internal/child_process:267:25	(anonymous)
node:electron/js2c/renderer_init:29:366	nextTick
node:internal/process/task_queues:104:18	Run Microtasks	
(anonymous)
plugin:obsidian-git:26544:46	callTaskParser
plugin:obsidian-git:25732:24	parser
plugin:obsidian-git:27767:11	parseStatusSummary
plugin:obsidian-git:27738:34	splitLine
plugin:obsidian-git:27626:19	data
plugin:obsidian-git:27636:16	(anonymous)
plugin:obsidian-git:27695:25	append
```

Not sure why obsidian git needs to parse anything if its only job is to git commit and push?
I don't have any fancy options enabled, just auto backup & auto pull

**Comment by PrinceHeadache** [comment] 2023-06-25 21:23
I'm having this issue as well, both in my own vault, and in a sandbox vault. I'm not connected to any repo or anything like that, so I'm not really sure what the issue is. It freezes so fast and so completely that I can't even check the console for errors! 

Turning off/deleting the plugin fixes the issue, but even having it enabled causes it to freeze in a matter of seconds.

I wish I could be more help in diagnosing the cause of the issue, but I at least wanted to contribute my experience to the conversation. Thank you!

**Closed** 2023-07-26 12:25 UTC

**Comment by pyinto** [comment] 2025-02-11 19:53
@A6rron have you fixed it? Having the same issue now.
