### ISSUE TITLE
[Bug]: Can't detect git in Linux (Ubuntu 22.04) (Obsidian Snap)

### ISSUE THREAD

**Issue by Krotau** [denolehov/obsidian-git#242] opened 2022-06-03 15:03 UTC
### Describe the bug

I installed obsidian and loaded my plugins. Every plugin works except Obsidian-Git.

It fails to load on start-up and gived the message "git obsidian error: Cannot run git command". I clearly have git installed and am using it manually to update the repository for now since the plugin is not working.

Below I pasted the error I get from the developer console.

I am no expert in snap environments but I think it might have to do with that.

### Relevant errors (if available)

```shell
app.js:1 Obsidian Developer Console
VM148:14142 loading Obsidian Git plugin
VM158:23703 loading markdown-table-editor plugin
VM159:32574 Loading Mind Map plugin
VM148:11057 Error: spawnSync git ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_errnoException (node:internal/errors:594:12)
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:821:24)
    at SimpleGit.isGitInstalled (eval at <anonymous> (app.js:1:1494667), <anonymous>:11053:57)
    at SimpleGit.eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:10754:16)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:66:61)
    at new Promise (<anonymous>)
    at __async (eval at <anonymous> (app.js:1:1494667), <anonymous>:50:10)
    at SimpleGit.setGitInstance (eval at <anonymous> (app.js:1:1494667), <anonymous>:10753:12)
    at new SimpleGit (eval at <anonymous> (app.js:1:1494667), <anonymous>:10750:10)
    at ObsidianGit.eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:14314:27)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:66:61)
    at new Promise (<anonymous>)
    at __async (eval at <anonymous> (app.js:1:1494667), <anonymous>:50:10)
    at ObsidianGit.init (eval at <anonymous> (app.js:1:1494667), <anonymous>:14312:12)
    at eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:14259:51)
    at t.<anonymous> (app.js:1:1443816)
    at app.js:1:234991
    at Object.next (app.js:1:235096)
    at s (app.js:1:233835)
isGitInstalled @ VM148:11057
VM148:11057 Error: spawnSync git ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_errnoException (node:internal/errors:594:12)
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:821:24)
    at SimpleGit.isGitInstalled (eval at <anonymous> (app.js:1:1494667), <anonymous>:11053:57)
    at SimpleGit.eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:10935:17)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:66:61)
    at new Promise (<anonymous>)
    at __async (eval at <anonymous> (app.js:1:1494667), <anonymous>:50:10)
    at SimpleGit.checkRequirements (eval at <anonymous> (app.js:1:1494667), <anonymous>:10934:12)
    at ObsidianGit.eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:14315:46)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:66:61)
    at new Promise (<anonymous>)
    at __async (eval at <anonymous> (app.js:1:1494667), <anonymous>:50:10)
    at ObsidianGit.init (eval at <anonymous> (app.js:1:1494667), <anonymous>:14312:12)
    at eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:14259:51)
    at t.<anonymous> (app.js:1:1443816)
    at app.js:1:234991
    at Object.next (app.js:1:235096)
    at s (app.js:1:233835)
isGitInstalled @ VM148:11057
VM148:14652 git obsidian error: Cannot run git command
```

### Steps to reproduce

0. Prerequisite: have git installed on the system
1. install obsidian as a snap on ubuntu 22.04
2. install obsidian-git plugin
3. restart obsidian
4. It fails to load

### Operating system

Linux

### Plugin version

1.25.3

**Comment by Vinzent03** [comment] 2022-06-07 07:42
Please search for existing issues before creating a new one.
Duplicate of #89.
Please read [this comment](https://github.com/denolehov/obsidian-git/issues/194#issuecomment-1053545759)

**Closed** 2022-06-07 07:42 UTC
