### ISSUE TITLE
[Bug]: Clone just quits without error message doing nothing on Android

### ISSUE THREAD

**Issue by crankedguy** [denolehov/obsidian-git#585] opened 2023-08-25 18:09 UTC
### Describe the bug

Hi,

we are having self-hosted Gitlab server, lots of repos, no problems anywhere.
Created a PAT for Obsidian with proper rights, we can also see the request from Obsidian get to the server but then Obsidian on the phone force quits without any error message or whatever.
The problem is that we cannot provide anything from our side, the request gets through to the server clean
`/git-upload-pack HTTP/1.1" 200 138239657` but nothing happens, the plugins creates a few .git directories and then as said Obsidian force quits.  
```
.git
   hooks
   info
   objects
      info
      pack
   refs
      heads
      tags
   config
   HEAD
```
are created, everything empty, and that's it. We tried several tokens, they all work completely normal when cloning the repo to elsewhere. e.g. PC, we also see in Gitlab that it recognized the token as it got into a "used" state, but we don't know how we should go on from here. Server logs are clean, Android is not our business, we are not really experts there apart from heavy using.

Any idea how we can investigate this further? We are on here for hours in the meanwhile, but stopping now because no idea what to do about it

### Steps to reproduce

Vanilla Obsidian install, only obsidian-git installed, trying to pull/clone repo from Gitlab with PAT
everything latest version
Android 13, Samsung Galaxy S22 Ultra
Kernel 5.10.136

### Operating system

Android

### Installation Method

None

### Plugin version

2.21.0

**Comment by Vinzent03** [comment] 2023-08-29 12:48
Sorry, but this is an issue I'm unable to fix. I think it's a memory issue which is caused by the package to reimplement git in js. Duplicate of #352

**Comment by crankedguy** [comment] 2023-08-29 13:05
Ok thanks for your reply. That sounds pretty bad as I have to find a completely other solution now, and they were all not really viable to me. My repo is around 120MB by the way.

**Comment by Vinzent03** [comment] 2023-08-29 18:27
I understand that, but there is sadly nothing I can do.

**Closed by Vinzent03** 2023-08-29 18:27 UTC
