### ISSUE TITLE
[Bug]: clone and fetch crash mobile app (ios16-iphone12_mini)

### ISSUE THREAD

**Issue by xNaCly** [denolehov/obsidian-git#381] opened 2022-11-19 21:34 UTC
### Describe the bug

While cloning a remote repo with correct credentials, the obsidian mobile app crashes. Pop-ups for fetching remote branches and initializing clone appear and disappear, however after 10-15 seconds the app crashes. I do not know how to access debug or error logs, neither do I know if the app nor this plugin is the root for the crash. Please let me know if there is a workaround available.

FYI: 

The repo contains around 2500 commits, 280 files and is ca. 350mb in size.

### Steps to reproduce

- create new Vault
- Install obsidian-git 
- input credentials
- run clone repo command
- insert remote url
- watch the application crash

### Operating system

iOS

### Plugin version

2.10.2

**Comment by mathisgauthey** [comment] 2022-11-23 06:56
Same problem on my Pixel 4A 5G (Android 12).

**Comment by zinzy** [comment] 2022-11-25 07:57
I've got 2400 files at 35MB on iOS 16.1.1, iPhone 12 Pro. 

Curiously, I did get all of this to work a couple of days ago.

**Comment by Vinzent03** [comment] 2022-11-26 12:07
Duplicate of #373

**Closed by Vinzent03** 2022-11-26 12:07 UTC
