### ISSUE TITLE
Would it be possible for this to use isomorphic-git?

### ISSUE THREAD

**Issue by douglasg14b** [denolehov/obsidian-git#91] opened 2021-07-15 01:03 UTC
I'm not sure if the Plugin API will let you add library dependencies, but instead of relying on the host for a GIT install, this could use a JS implementation https://github.com/isomorphic-git/isomorphic-git.

Again, not sure what limitations the Plugin API has, but with this you could seamlessly setup the repo without external dependencies. Making it possible to sync between multiple devices, like the `obsidian sync` feature.

**Comment by douglasg14b** [comment] 2021-07-15 01:15
After some more research I think this might be very possible.

**Comment by Vinzent03** [comment] 2021-07-15 09:54
Thanks for your will to help, but if you had read the thread in #57 you would have seen that I already [mentioned](https://github.com/denolehov/obsidian-git/issues/57#issuecomment-817327415) that I will use isomorphic-git. I even stated it as a possible solution in the issue description.

I am closing this, because it's a duplicate of #57.

**Closed by Vinzent03** 2021-07-15 09:54 UTC
