### ISSUE TITLE
[Bug]: Cannot individually stage files with accented characters in their file names

### ISSUE THREAD

**Issue by jsmm** [denolehov/obsidian-git#142] opened 2021-11-26 12:27 UTC
### Describe the bug

In this plugin's Source Control View panel, files with accented characters in their file names cannot be individually staged.

### Relevant errors (if available)

```shell
`pathspec` notifies a fatal error: file name did not match any files. 
```

### Steps to reproduce

Error notification for a file named "W- redención":

![Obsidian-git-pathspec](https://user-images.githubusercontent.com/2811090/143580111-70903db9-6bff-4942-ad22-0a7be4415774.png)

### Expected Behavior

Processing accented characters (such as á, é, í, ó, ú, ü, ñ) is necessary for the plugin to be used by users who write in Spanish, French, Italian, etc.

### Addition context

When the backup is automatically created in bulk for all files, they are staged and committed correctly.

### Operating system

macOS

**Comment by Vinzent03** [comment] 2021-11-26 21:06
Duplicate of #121. Please use the fix provided in this issue.

**Closed by Vinzent03** 2021-11-26 21:06 UTC
