### ISSUE TITLE
[Bug]: Android: Obsidian crashes when trying to clone remote repo

### ISSUE THREAD

**Issue by johnmhm** [denolehov/obsidian-git#422] opened 2023-01-10 05:35 UTC
### Describe the bug

I am following the steps on https://github.com/denolehov/obsidian-git/wiki/Installation#mobile

Everything goes as described until step 13: `Clone should start. Popup notifications (if not disabled) will display the progress. Do not exit until a popup appears requesting that you "Restart Obsidian".`

Pop-ups come up with `Initializing clone..` and so forth, and then Obsidian closes without any notice. When reopening Obsidian the repo was not cloned. 

### Steps to reproduce

On Android 10 mobile phone
Follow the steps on https://github.com/denolehov/obsidian-git/wiki/Installation#mobile

### Operating system

Android

### Plugin version

2.15.0

**Comment by Vinzent03** [comment] 2023-01-10 08:58
Duplicate of #384

**Closed by Vinzent03** 2023-01-10 08:58 UTC
