### ISSUE TITLE
[Bug]: "Disable Notifications" Setting not respected on mobile

### ISSUE THREAD

**Issue by bd-g** [denolehov/obsidian-git#359] opened 2022-10-31 14:37 UTC
### Describe the bug

The setting is respected on desktop - I do not see any messages from Obsidian Git. However, on mobile, I get constant pop-ups from Obsidian git, telling me everytime there is a push, pull, index, commit, etc. This is even more frustrating on mobile that on desktop, because the status bubbles fill up a third of my screen and are more distracting.

### Steps to reproduce

1. Setup an Obsidian Vault that is also a git repo across a desktop device and an iOS device. 
2. Either manually (or just wait for automatic commit/push/pull if enabled) have Obsidian Git perform git commands on your vault on both desktop and mobile.

### Expected Behavior

I should only get error messsages from the Obsidian Git extension across all plaforms.

### Addition context

I have a single Obsidian fault stored in a git repo that is synced across desktop and mobile (iOS) using Obsidian Git. I have the "Disable Notifications" setting enabled, meaning I should only see error notifications, not standard notifications like "Index x files" or "Pull".

### Operating system

Linux

### Plugin version

2.8.0

**Comment by Vinzent03** [comment] 2022-11-02 21:33
Duplicate of #292

**Closed by Vinzent03** 2022-11-02 21:33 UTC
