### ISSUE TITLE
[Bug]: App crashes when cloning existing repo on Android

### ISSUE THREAD

**Issue by Skydler** [denolehov/obsidian-git#400] opened 2022-12-13 14:23 UTC
### Describe the bug

When I follow the steps for cloning an existing git repo on my Android phone it reaches this stage...
![image](https://user-images.githubusercontent.com/32437504/207357460-d94bbcb3-5e72-4acd-9dfa-0de8b46cf9ec.png)

And then the app crashes without a message.. No files downloaded. My repo is 58MB so I don't think that's the problem. Any ideas on what could it be? Or how could I debug it?

### Steps to reproduce

Follow the installation instructions for Android on cloning an existing Github repository

### Expected Behavior

My repository is cloned successfully and I have access to my vault on my phone

### Operating system

Android

### Plugin version

2.13.0

**Comment by Vinzent03** [comment] 2022-12-13 14:26
Duplicate of #384

**Closed by Vinzent03** 2022-12-13 14:26 UTC
