### ISSUE TITLE
Git crash on pull

### ISSUE THREAD

**Issue by Rayffer** [denolehov/obsidian-git#601] opened 2023-09-10 14:10 UTC
### Describe the bug

When I pull a repo that contains images it crashes consistenly and I can not operate with it from Android. 

### Steps to reproduce

Create a git repo.
Populate it with content and check that you can pull regularly.
Start adding images from a Windows desktop version of the app and sync.
Pull from the Android version of the app and observe that a crash happens

### Expected Behavior

From Android I can pull without a problem when a repo has image files. 

### Addition context

I need to find out how to find error logs to incluye them, any help? 

### Operating system

Android

### Installation Method

None

### Plugin version

2.22

**Comment by Vinzent03** [comment] 2023-09-11 10:42
Sorry, but I can't do anything about it. It's a memory issue with an underlying library. Duplicate of #352

**Closed by Vinzent03** 2023-09-11 10:42 UTC
