### ISSUE TITLE
[Bug]: Seems to be stuck on git: committing changes...

### ISSUE THREAD

**Issue by NorseGaud** [denolehov/obsidian-git#136] opened 2021-11-14 18:39 UTC
### Describe the bug

1.15.0

<img width="520" alt="Screen Shot 2021-11-14 at 1 35 38 PM" src="https://user-images.githubusercontent.com/5896030/141694034-eefecded-5afc-45f5-a3e8-31c9e3c2fd75.png">

<img width="638" alt="Screen Shot 2021-11-14 at 1 35 15 PM" src="https://user-images.githubusercontent.com/5896030/141694057-239e9dd3-09da-453a-b94f-7d0edc0441e1.png">
>
<img width="1561" alt="Screen Shot 2021-11-14 at 1 38 54 PM" src="https://user-images.githubusercontent.com/5896030/141694101-b0af6e78-6d65-40a2-a707-de3810e3e072.png">
<img width="1544" alt="Screen Shot 2021-11-14 at 1 38 49 PM" src="https://user-images.githubusercontent.com/5896030/141694102-8a533654-b791-4a02-8708-1434a1b1bbf9.png">

I can manually add, commit, and then push, but shouldn't the plugin handle this?

### Steps to reproduce

Unsure

### Operating system

macOS

**Comment by Alphinux** [comment] 2021-11-21 13:30
Hi NorseGaud,
I experienced the same problem. Here's the solution I found:
Try commiting the changes manually with `git commit`. You'll probably get an error like 
> Identity of author unknown
To solve this type `git config --global user.name "Your Name"` or `--global user.email "Your@Email.com`.
You now should be able to commit in Obsidian and it should say 
> Git: Commited xx files
Hope it also works for you.

**Comment by NorseGaud** [comment] 2021-11-21 13:41
Not my problem: I can manually add commit and push

**Comment by tapokshot** [comment] 2021-11-23 21:10
had the same problem 
I tried turn on off  'Disable push' after reboot and then push started works

**Comment by Vinzent03** [comment] 2021-12-06 09:14
@NorseGaud Can you try disabling pushing on backup and run the backup. If a command runs forever and there is no response, it's most of the time waiting for the username and password to be entered.

**Comment by ethyi** [comment] 2021-12-20 08:30
Hey NorseGaud,

Hit ctrl+shift+i on obsidian, run the backup, and show an image of the error on dev console, if there is one.

**Comment by Sobieg** [comment] 2021-12-27 06:57
Hi! I have same problem with creating backups.

I can manualy create commit and push from terminal, but can't create backup from obsidian.

I have this in Developer Console:

![Снимок экрана 2021-12-27 в 09 54 44](https://user-images.githubusercontent.com/24317894/147443682-67e3d4e7-a837-4dcd-9824-23986e7bb312.png)

I think the problem is that I have enabled signing of commits on github, but I can still use the git cli, so it might not be right.

**Comment by ethyi** [comment] 2021-12-27 07:28
Does nothing go through, or does it commit but not push?

**Comment by Sobieg** [comment] 2021-12-27 08:06
"Create backup" does `git add *` in my perspective: new files added, and modified files is staged. But commit doesn't.

**Comment by Vinzent03** [comment] 2021-12-30 19:34
@Sobieg Your problem is gpg signing. Do you have a passphrase for that key? If yes, it's related to #133

**Comment by limonkufu** [comment] 2022-01-03 23:16
Hi, I had the same issue but my gpg key wasn't using a passphrase. The workaround described here worked for me: https://github.com/denolehov/obsidian-git/issues/21#issuecomment-735436767

Find your gpg lives:
`$ which gpg`

Mine is on `/usr/local/bin/gpg`, so configure git to use it:

`$ git config --global gpg.program /usr/local/bin/gpg`

**Comment by chakrakan** [comment] 2022-03-25 05:51
> Hi, I had the same issue but my gpg key wasn't using a passphrase. The workaround described here worked for me: [#21 (comment)](https://github.com/denolehov/obsidian-git/issues/21#issuecomment-735436767)
> 
> Find your gpg lives: `$ which gpg`
> 
> Mine is on `/usr/local/bin/gpg`, so configure git to use it:
> 
> `$ git config --global gpg.program /usr/local/bin/gpg`
> 
> I did force-reload afterwards but I don't think that's necessary

This didn't work for me, but what actually did work was using something like `gpg-suite-no-mail` (https://formulae.brew.sh/cask/gpg-suite-no-mail). Then the auto-push feature worked as well.

**Comment by koriavinash1** [comment] 2022-07-14 06:47
I'm facing a similar issue, where the changes are automatically committed but are not pushed, any pointer on how to fix it? I tried fixing global username details and ssh keys still didn't work.

**Closed** 2022-07-15 10:24 UTC
