### ISSUE TITLE
[BUG] Backup on Android leads to buffer error

### ISSUE THREAD

**Issue by 0xShkk** [denolehov/obsidian-git#307] opened 2022-09-09 19:02 UTC
Hi,

I have a repo which contains a few Pictures. Its about 40 MB in size in total.

The strange thing is that sometimes it works to do a backup so the push completes and everything is completely in snyc.

And then out of nowhere when trying to do a backup it says initializing push and directly after that buffer error.

It's like yesterday evening it is working then the next morning it says buffer error and then few hours later it's working again. Only adding few lines of text between the backup attempts.

Could I debug this somehow or is my repo already too big?

![Screenshot_20220909-210547_Obsidian.jpg](https://user-images.githubusercontent.com/51774233/189425503-030fb5d4-f7f2-40eb-b784-dcaf9f1ff3f1.jpg)

Bug is on Android and Plugin version is 2.1.0

**Comment by Vinzent03** [comment] 2022-09-09 21:02
I haven't done much research, but I guess it depends on the available ram on your device. E.g. how many other apps you have opened. 40mb isn't that big. I thought the limit would be higher.

**Comment by 0xShkk** [comment] 2022-09-10 14:44
Thats a good point. Will try to clean the cache before doing a backup and see how it goes

**Comment by Vinzent03** [comment] 2022-09-12 15:14
Since there isn't really anything, I can do to fix this. I'm closing this now.

**Closed by Vinzent03** 2022-09-12 15:14 UTC

**Comment by sakha002** [comment] 2022-09-12 16:40
Hi, I am getting same buffer error when attempting to push, and my repo is tiny , the commit said 10 files changed,  and device memory is big. I also closed all other apps. Any suggestions on what to do? I hope I can avoid cloning again

**Comment by 0xShkk** [comment] 2022-09-12 18:47
> @Vinzent03 Hi, I am getting same buffer error when attempting to push, and my repo is tiny , the commit said 10 files changed,  and device memory is big. I also closed all other apps. Any suggestions on what to do? I hope I can avoid cloning again 

Just wait and try again. Its working again after a while but its definately buggy. Sad that this is not investigated any further..

**Comment by 0xShkk** [comment] 2022-09-12 18:48
Also, clearing cache after getting the error didnt help.

**Comment by c0deZ3R0** [comment] 2022-09-16 15:41
I have the same problem with a small repo. Can't get mobile to sync without buffer error. Have cleared the cache with no luck.

**Comment by 0xShkk** [comment] 2022-09-16 17:26
@Vinzent03 maybe some advises on one could debug this?

It seems like there are a few people experiencing the issue

**Comment by 0xShkk** [comment] 2022-09-16 17:27
Or should I open the bug elsewhere?

Any help would be greatly appreciated

**Comment by Vinzent03** [comment] 2022-09-20 10:48
As said before I'm really sorry it's not working on your device, but I think there is nothing I can do. The underlying lib is not very memory saving. I know that's bad for a mobile. plugin, but that's the only way I found to make it work for at least some users.

**Comment by 0xShkk** [comment] 2022-09-20 14:36
Ok no worries than. It works most of the time though 

Thanks for your work and sharing

**Comment by 0xShkk** [comment] 2022-10-02 19:20
Leaving this here in case someone got the same troubles and looks for a solution.

When you exclude the Obsidian app from memory management in Android settings, the plugin works just fine. I can do this in device management settings but this setting may dependt on the device.

**Comment by Takaishisama** [comment] 2022-10-08 16:15
> 

Could you please explain further? Can't seem to find how

**Comment by blqke** [comment] 2022-10-16 11:30
@Takaishisama 

Succeeded to exclude the app from memory management, it is now working as expected. It depends of your android device, here how you can find the settings screen:

![New Project](https://user-images.githubusercontent.com/1248148/196032881-5b9a5fc0-40c9-45b1-9188-297a61d0d969.jpg)

**Comment by penfold00** [comment] 2022-11-07 21:28
I'm experiencing the same problem with a small vault and small files. 
I am using a Samsung Galaxy S10, Android 12.

The sync worked 1 or 2 times, now there's a buffer error every time and it's not pushing/pulling. 
Clearing the app cache didn't help. 
I checked the memory usage of the app, Android says max usage has been 333 MB, which seems normal. Average usage of 107 MB seems a bit high, but still fine. 

I am very confused by the proposed solution by @0xShkk and @blqke. 
@blqke you are changing the battery usage in your screenshot, which should not have anything to do with memory management?!
@0xShkk is that what you meant? I cannot find a setting to change memory usage behaviour of an app. 

Also, might the sync of the app settings between PC and Android be a problem? Should these be excluded using .gitignore?

Thanks for your help!

**Comment by 0xShkk** [comment] 2022-11-08 07:04
@penfold00 

I meant exactly this. It may be that this setting can't be found on all devices but just guessing here. For me it still works fine

**Comment by HarvsG** [comment] 2023-02-01 17:41
> As said before I'm really sorry it's not working on your device, but I think there is nothing I can do. The underlying lib is not very memory saving. I know that's bad for a mobile. plugin, but that's the only way I found to make it work for at least some users.

isomorphic git supports reducing the clone depth: https://isomorphic-git.org/docs/en/clone
You may find this makes things less memory intensive as there is no need to clone the entire git history - particularly if users have accidentally have larger files in their git history

**Comment by Vinzent03** [comment] 2023-02-26 13:01
@HarvsG Great idea. Available in v2.17.0

**Comment by bszewc3203** [comment] 2023-06-17 21:58
So it seems this error doesn't have a fix yet which kinda sucks since I have the same problem. Cloning a vault crashes the app. Tried this battery option even though it is strange like the other person said and it didn't work. Also tried turning off every other app that was running.

**Comment by btmurrell** [comment] 2023-07-31 04:10
I am having this problem 100% of the time. My repo is only 1.5MB. I am on Android. I have tried the memory and the battery suggestions above with no success. 

@Vinzent03, could you share what other configurations or conditions might trigger the "buffer error"?  Is there any obsidian-git logging I could capture?

I have searched isomorphic-git for "buffer error" and it does not appear on the web or in the obsidian-git repo.   

Thank you!

**Comment by btmurrell** [comment] 2023-07-31 16:48
FYI @Vinzent03, and for any others that may land here... For my case, it was a "user shot self in foot", "user solved self" PEBKAC case... I was curious about what other factors might contribute to this error.  I can tell you one...

Because of other errors I had experienced, I had removed and re-cloned my repo more than once. In one reconfiguration, I moved my repo to a subfolder of its original location.  So, originally my repo was in something like `folder-a/notes` and I moved it into `folder-a/newhome/notes`.  To do this, I removed my `folder-a/notes` directory, then re-cloned into `folder-a/newhome/notes`.  MY problem was that I left behind the `folder-a/.obsidian` directory.... and so, I ended up with two `.obsidian` folders in a hierarchy... so, as we know, the obsidian-git configs are under the `.obsidian/plugins` directory... and I assume there is an "up the chain" precedence in obsidian-git and with two conflicting configs, that was the cause of my "buffer error".   After removing my parent directory `.obsidian` folder, my issue was resolved.

**Comment by MalachiMcintosh** [comment] 2023-10-30 10:36
First off thanks to the maintainers for this fantastic plugin. 
I just wanted to comment for anyone who comes across this issue to say I've found a workaround that is currently working for me (Samsung Galaxy S21, Android 13).

In Settings -> Battery and Device Care -> Memory I increased the RAM Plus (which I assume is swap) to 8GB (seems overkill) and added Obsidian to the "Excluded apps" list. I haven't had any buffer error issues since. Still watching #572 intently though!

**Comment by vJourneyman** [comment] 2024-02-14 07:25
Wondering if people could report the versions of Android, phone, and RAM with their problem.
I'm able to do an initial sync from remote repo, but not a backup after making a small change. 
buffer error



Pixel 5, 8GB RAM, Android 14 with Nov 5, 2023 security patch;

Obsidian maxed out at 3.9 GB of RAM usage.

[How to Check RAM on Android 14?](https://www.youtube.com/watch?v=HkAcFnZ6cUg)

**Comment by Exanite** [comment] 2024-07-03 05:04
Also getting this issue. Pixel 4a with 6 GB ram.
Obsidian shows as using only 280 MB of ram. I've also set it to unrestricted.

I've had this happen twice. The first one I don't remember what caused it, but the second seems to be caused by attempting to pull when the remote contains changes that modify a file that is already locally modified.

Deleting the vault and re-cloning the repo has fixed it in both cases for me. Restarting Obsidian doesn't seem to do anything (I haven't tried force killing the app though).

**Comment by massivedynamics** [comment] 2025-01-12 17:50
I don't have this error with following setup for months. Along the line I first modify the git config file because of the comments about file size. It didn't fix until I set gitignore. I added my git config to below anyway.

1. On PC, git clone {repo https url}
2. set gitignore to 
```
.obsidian/workspace*
.obsidian/plugins/obsidian-git/data*
```
3. modify git config
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
	autocrlf = input
[remote "origin"]
	url = https://{your name}:{your access token}@github.com/{your name}/{your vault}.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[user]
	email = {your email}
	name = {your name}
[branch "main"]
	remote = origin
	merge = refs/heads/main
[mergetool "meld"]
	useAutoMerge = true
	
```
4. Try pull/commit/push
5. Copy vault folder to mobile and open folder as vault
6. Set obsidian git plugin on PC and mobile because its settings are now in gitignore. 
![image](https://github.com/user-attachments/assets/07cff614-7d70-4ed9-8d5b-f16618bec248)
![image](https://github.com/user-attachments/assets/559d7fd0-cb61-46ca-b28b-e6943b9fbb78)

Cheers
